// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTVb_O_yibqPjQNLbEIcZj275nh8UeOjg',
    appId: '1:279813429718:web:9b74f6a327d5270842ac77',
    messagingSenderId: '279813429718',
    projectId: 'agrishield-71213',
    authDomain: 'agrishield-71213.firebaseapp.com',
    storageBucket: 'agrishield-71213.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmztirWKOZXeI1GD9F33cr0nv7uQVEVxk',
    appId: '1:279813429718:android:713ca284b6f5027142ac77',
    messagingSenderId: '279813429718',
    projectId: 'agrishield-71213',
    storageBucket: 'agrishield-71213.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgSlvQ3gcgzl4HQk9XsvbxhaUmhLVcrvk',
    appId: '1:279813429718:ios:d1c79c743dc858f942ac77',
    messagingSenderId: '279813429718',
    projectId: 'agrishield-71213',
    storageBucket: 'agrishield-71213.firebasestorage.app',
    iosBundleId: 'com.example.agrishield2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgSlvQ3gcgzl4HQk9XsvbxhaUmhLVcrvk',
    appId: '1:279813429718:ios:d1c79c743dc858f942ac77',
    messagingSenderId: '279813429718',
    projectId: 'agrishield-71213',
    storageBucket: 'agrishield-71213.firebasestorage.app',
    iosBundleId: 'com.example.agrishield2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTVb_O_yibqPjQNLbEIcZj275nh8UeOjg',
    appId: '1:279813429718:web:558611de95da322c42ac77',
    messagingSenderId: '279813429718',
    projectId: 'agrishield-71213',
    authDomain: 'agrishield-71213.firebaseapp.com',
    storageBucket: 'agrishield-71213.firebasestorage.app',
  );
}
